### ISSUE TITLE
【依頼】フリマアプリ挙動確認

### ISSUE THREAD

**Issue by impress85** [m85hayashi/furima-30550#9]
以下、確認よろしくお願いします！
---
# URL
https://furima-30550.herokuapp.com/

# Basic認証のIDとパスワード
* admin
* 1234

# 出品者用のメールアドレスとパスワード
* taro@xxx
* 123abc

# 購入者用のメールアドレスとパスワード
* jiro@xxx
* 123abc

# 購入用カードの番号・期限・セキュリティコード
* カード番号　　4242424242424242
* 期限　　　　　12月22年
* セキュリティコード　　123

**Comment by tech-oa** [comment]
m85hayashi さん、ご提出ありがとうございます！
挙動確認させて頂きましたが、全く問題ございませんでしたのでLGTMとさせて頂きます🎉
おめでとうございます！


**※確認したのは必須機能のみで追加実装した機能については確認していません。
そのため追加機能を実装している場合は、正しく想定通りの挙動であるかご自身で再度確認をお願いいたします。**

**Comment by impress85** [comment]
どうもありがとうございました！
